blueprint:
  name: How's the Weather?
  description: Ask "How's the Weather?" and ViewAssist will respond with the weather and show the weather view.
  domain: automation
  input:
    dashboard:
      name: Dashboard
      description: The base dashboard for View Assist
      default: "/dashboard-viewassist/weather"
    group_entity: 
      name: Group Entity
      description: The group entity that holds the list of ViewAssist 
      default: "group.assist_satellites"
    weather_entity: 
      name: Weather Entity
      description: The entity that provides weather information.
      default: "weather.home"
    
# Main automation configuration
alias: VIEWASSIST - How's the weather
description: "Find out what the weather is"
trigger:
  - platform: conversation
    command: How's the weather
variables:
  group_entity: !input group_entity
  weather_entity: !input weather_entity
condition: []
action:
  - set_conversation_response: >-
      Its {{ state_attr('{weather_entity}', 'temperature') }} degrees and
      {{states.{weather_entity}.state}}
    enabled: true
  - variables:
      target_satellite_device: |-
        {% for sat in expand('{group_entity}') %}
          {% if device_id(sat.attributes.mic_device)  == trigger.device_id %}
            {{ sat.name }}
          {% endif %}
        {% endfor %}
      target_display_device: "{{ device_id (state_attr(target_satellite_device, 'display_device')) }}"
      target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device') }}"
    enabled: true
  - service: browser_mod.navigate
    data:
      path: !input dashboard
    target:
      device_id: "{{ target_display_device }}"
mode: single
