blueprint:
  name: How's the Weather?
  description: Ask "How's the Weather?" and ViewAssist will respond with the weather and show the weather view.
  domain: automation
  input:
    dashboard: /dashboard-viewassist/weather
    group_entity: group.assist_satellites
    weather_entity: weather.home
    
#entities that need to be variables
#weather.home
#group.assist_satellites
#/dashboard-viewassist/weather


#comment
alias: VIEWASSIST - How's the weather
description: "Find out what the weather is"
trigger:
  - platform: conversation
    command: How's the weather
condition: []
action:
  - set_conversation_response: >-
      Its {{ state_attr('weather.home', 'temperature') }} degrees and
      {{states.weather.home.state}}
    enabled: true
  - variables:
      target_satellite_device: |-
        {% for sat in expand('group.assist_satellites') %}
          {% if device_id(sat.attributes.mic_device)  == trigger.device_id %}
            {{ sat.name }}
          {% endif %}
        {% endfor %}
      target_display_device: "{{ device_id (state_attr(target_satellite_device, 'display_device')) }}"
      target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device') }}"
    enabled: true
  - service: browser_mod.navigate
    data:
      path: !input dashboard
    target:
      device_id: "{{ target_display_device }}"
mode: single
